version: "3.8"
 
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: manager
      MYSQL_DATABASE: taskmanager
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
 
  flask-api:
    build: ./flask-api
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./flask-api/.env
    depends_on:
      - mysql
    links:
      - mysql
 
  node-api:
    build: ./node-task-api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./node-task-api/.env
    depends_on:
      - mongodb
    links:
      - mongodb
 
  mongodb:
    image: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
 
volumes:
  mysql_data:
  mongodb_data:
