version: '3.8'
 
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: manager
      MYSQL_DATABASE: taskmanager
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
 
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
 
  flask-api:
    build: ./flask-api
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      - FLASK_ENV=development
 
  node-api:
    build: ./node-task-api
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - flask-api
    environment:
      - NODE_ENV=development
 
volumes:
  mysql_data:
  mongo_data: